################################################################
# Cooldown in between entering certain block-altering commands #
################################################################
Command-Cooldown: 3

################################################################################
# Block volume limit per command (with the exception of the plotclear command) #
################################################################################
Block-Volume-Limit: 50000

#################################################################################################################
# Pre-defined volume of the plot being cleared. this prevents any possibility of the wrong region being cleared #
#################################################################################################################
Plot-Clear-Volume: 22500000

###################################################################
# Pre-defined y level that a plotclear regenerates its terrain to #
###################################################################
Plot-Y-Level: 65 #this is CV specific. used for cvclearplot command to regen cleared plot to a certain Y-level

################################################################################################################
# Plotclears that can run at the same time. admin plotclears (ie /plotclear plot_2) are exempt from this limit #
################################################################################################################
Plot-Clears-Running-At-A-Time: 2

###############################################
# Entities that the plotclear command removes #
###############################################
Plot-Clear-Entity:
  - DROPPED_ITEM
  - MINECART
  - MINECART_CHEST
  - MINECART_FURNACE
  - MINECART_TNT
  - MINECART_HOPPER
  - MINECART_COMMAND
  - MINECART_MOB_SPAWNER
  - PAINTING
  - ITEM_FRAME
  - ARMOR_STAND

################################################################################################
# Blocks that are banned from being used with a command (plotclear command is exempt obviously #
################################################################################################
Block-Blacklist:
  - FIRE
  - SOUL_FIRE
  - WATER
  - LAVA
  - CHEST
  - FURNACE
  - JUKEBOX
  - ENDER_CHEST
  - ANVIL
  - CHIPPED_ANVIL
  - DAMAGED_ANVIL
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - PAINTING
  - ITEM_FRAME
  - PLAYER_HEAD
  - PLAYER_WALL_HEAD
  - SKELETON_SKULL
  - WITHER_SKELETON_SKULL
  - ZOMBIE_HEAD
  - ZOMBIE_WALL_HEAD
  - CREEPER_HEAD
  - ZOMBIE_WALL_HEAD
  - DRAGON_HEAD
  - DRAGON_WALL_HEAD
  - ARMOR_STAND
  - END_CRYSTAL
  - BARREL
  - SMOKER
  - BLAST_FURNACE
  - TNT
  - TRAPPED_CHEST
  - HOPPER
  - MINECART
  - CHEST_MINECART
  - FURNACE_MINECART
  - TNT_MINECART
  - HOPPER_MINECART
  - SAND
  - RED_SAND
  - GRAVEL
  - WHITE_CONCRETE_POWDER
  - ORANGE_CONCRETE_POWDER
  - PINK_CONCRETE_POWDER
  - LIGHT_BLUE_CONCRETE_POWDER
  - YELLOW_CONCRETE_POWDER
  - MAGENTA_CONCRETE_POWDER
  - LIME_CONCRETE_POWDER
  - GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_CONCRETE_POWDER
  - CYAN_CONCRETE_POWDER
  - PURPLE_CONCRETE_POWDER
  - BLUE_CONCRETE_POWDER
  - BROWN_CONCRETE_POWDER
  - GREEN_CONCRETE_POWDER
  - RED_CONCRETE_POWDER
  - BLACK_CONCRETE_POWDER
  - SEA_PICKLE
  - TUBE_CORAL
  - BRAIN_CORAL
  - BUBBLE_CORAL
  - FIRE_CORAL
  - HORN_CORAL
  - DEAD_BRAIN_CORAL
  - DEAD_BUBBLE_CORAL
  - DEAD_FIRE_CORAL
  - DEAD_HORN_CORAL
  - DEAD_TUBE_CORAL
  - TUBE_CORAL_FAN
  - BRAIN_CORAL_FAN
  - BUBBLE_CORAL_FAN
  - FIRE_CORAL_FAN
  - HORN_CORAL_FAN
  - DEAD_TUBE_CORAL_FAN
  - DEAD_BRAIN_CORAL_FAN
  - DEAD_BUBBLE_CORAL_FAN
  - DEAD_FIRE_CORAL_FAN
  - DEAD_HORN_CORAL_FAN
  - COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - CHAIN_COMMAND_BL0CK
  - CONDUIT
  - DRAGON_EGG
  - END_PORTAL
  - END_GATEWAY
  - NETHER_PORTAL
  - SPAWNER