Command-Cooldown: 3
Block-Volume-Limit: 50000
Plot-Clear-Volume: 22500000 #this is CV specific. the volume of a player creative plot
Plot-Y-Level: 65 #this is CV specific. used for cvclearplot command to regen cleared plot to a certain Y-level

Plot-Clear-Entity:
  - DROPPED_ITEM
  - MINECART
  - CHEST_MINECART
  - FURNACE_MINECART
  - TNT_MINECART
  - HOPPER_MINECART
  - PAINTING
  - ITEM_FRAME
  - ARMOR_STAND

Block-Blacklist:
  - FIRE
  - WATER
  - LAVA
  - CHEST
  - FURNACE
  - JUKEBOX
  - ENDER_CHEST
  - ANVIL
  - CHIPPED_ANVIL
  - DAMAGED_ANVIL
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - PAINTING
  - ITEM_FRAME
  - PLAYER_HEAD
  - SKELETON_SKULL
  - WITHER_SKELETON_SKULL
  - ZOMBIE_HEAD
  - CREEPER_HEAD
  - DRAGON_HEAD
  - ARMOR_STAND
  - END_CRYSTAL
  - BARREL
  - SMOKER
  - BLAST_FURNACE
  - TNT
  - TRAPPED_CHEST
  - HOPPER
  - MINECART
  - CHEST_MINECART
  - FURNACE_MINECART
  - TNT_MINECART
  - HOPPER_MINECART
  - SAND
  - RED_SAND
  - GRAVEL