main: org.cubeville.cvworldedit.CVWorldEdit
name: CVWorldEdit
version: 1.18
api-version: 1.18
description: 'CVWorldEdit Plugin'
author: ToeMan_
depend: [WorldGuard,WorldEdit,CVTools]
commands:
  cvhelp:
    aliases: wehelp
    permission: CVWorldEdit.selection.commands
  cvwand:
    aliases: wewand
    permission: CVWorldEdit.selection.commands
  cvpos1:
    aliases: wepos1
    permission: CVWorldEdit.selection.commands
  cvpos2:
    aliases: wepos2
    permission: CVWorldEdit.selection.commands
  cvhpos1:
    aliases: wehpos1
    permission: CVWorldEdit.selection.commands
  cvhpos2:
    aliases: wehpos2
    permission: CVWorldEdit.selection.commands
  cvexpand:
    aliases: weexpand
    permission: CVWorldEdit.selection.commands
  cvcontract:
    aliases: wecontract
    permission: CVWorldEdit.selection.commands
  cvselection:
    aliases: weselection
    permission: CVWorldEdit.selection.commands
  cvsel:
    aliases: wesel
    permission: CVWorldEdit.selection.commands
  cvsize:
    aliases: wesize
    permission: CVWorldEdit.selection.commands
  cvcopy:
    aliases: wecopy
    permission: CVWorldEdit.execute.commands
  cvpaste:
    aliases: wepaste
    permission: CVWorldEdit.execute.commands
  cvrotate:
    aliases: werotate
    permission: CVWorldEdit.execute.commands
  cvset:
    aliases: weset
    permission: CVWorldEdit.execute.commands
  cvwalls:
    aliases: wewalls
    permission: CVWorldEdit.execute.commands
  cvfaces:
    aliases: wefaces
    permission: CVWorldEdit.execute.commands
  cvreplace:
    aliases: wereplace
    permission: CVWorldEdit.execute.commands
  cvmove:
    aliases: wemove
    permission: CVWorldEdit.execute.commands
  cvundo:
    aliases: weundo
    permission: CVWorldEdit.execute.commands
  cvredo:
    aliases: weredo
    permission: CVWorldEdit.execute.commands
  cvclearhistory:
    aliases: weclearhistory
    permission: CVWorldEdit.execute.commands
  cvclearclipboard:
    aliases: weclearclipboard
    permission: CVWorldEdit.execute.commands
  cvclearplot:
    aliases: weclearplot
    permission: CVWorldEdit.clearplot.command

permissions:
  CVWorldEdit.selection.commands:
    description: Permissions to cvwand, cvpos1, cvpos2, cvexpand, cvcontract, cvsel, cvselection, and cvsize
    default: op
  CVWorldEdit.execute.commands:
    description: Permissions to cvcopy, cvpaste, cvset, cvreplace, cvundo, cvredo, and cvclearhistory
    default: op
  CVWorldEdit.clearplot.command:
    description: Permission to the cvclearplot command
    default: op