main: org.cubeville.cvworldedit.CVWorldEdit
name: CVWorldEdit
version: 0.1
api-version: 1.16
description: 'CVWorldEdit Plugin'
author: ToeMan_
depend: [WorldGuard,WorldEdit,CVTools]
commands:
  cvhelp:
    permission: CVWorldEdit.selection.commands
  cvwand:
    permission: CVWorldEdit.selection.commands
  cvpos1:
    permission: CVWorldEdit.selection.commands
  cvpos2:
    permission: CVWorldEdit.selection.commands
  cvexpand:
    permission: CVWorldEdit.selection.commands
  cvcontract:
    permission: CVWorldEdit.selection.commands
  cvselection:
    permission: CVWorldEdit.selection.commands
  cvsel:
    permission: CVWorldEdit.selection.commands
  cvsize:
    permission: CVWorldEdit.selection.commands
  cvcopy:
    permission: CVWorldEdit.execute.commands
  cvpaste:
    permission: CVWorldEdit.execute.commands
  cvrotate:
    permission: CVWorldEdit.execute.commands
  cvset:
    permission: CVWorldEdit.execute.commands
  cvwalls:
    permission: CVWorldEdit.execute.commands
  cvfaces:
    permission: CVWorldEdit.execute.commands
  cvreplace:
    permission: CVWorldEdit.execute.commands
  cvmove:
    permission: CVWorldEdit.execute.commands
  cvundo:
    permission: CVWorldEdit.execute.commands
  cvredo:
    permission: CVWorldEdit.execute.commands
  cvclearhistory:
    permission: CVWorldEdit.execute.commands
  cvclearclipboard:
    permission: CVWorldEdit.execute.commands
  cvclearplot:
    permission: CVWorldEdit.clearplot.command

permissions:
  CVWorldEdit.selection.commands:
    description: Permissions to cvwand, cvpos1, cvpos2, cvexpand, cvcontract, cvsel, cvselection, and cvsize
    default: op
  CVWorldEdit.execute.commands:
    description: Permissions to cvcopy, cvpaste, cvset, cvreplace, cvundo, cvredo, and cvclearhistory
    default: op
  CVWorldEdit.clearplot.command:
    description: Permission to the cvclearplot command
    default: op