main: org.cubeville.cvworldedit.CVWorldEdit
name: CVWorldEdit
version: 1.21.8
api-version: 1.21.8
description: 'CVWorldEdit Plugin'
author: ToeMan_
depend: [WorldGuard,WorldEdit,CVTools]
commands:
  cvhelp:
    aliases: wehelp
    permission: cvworldedit.help.command
  cvwand:
    aliases: wewand
    permission: cvworldedit.selection.commands
  cvpos1:
    aliases: wepos1
    permission: cvworldedit.selection.commands
  cvpos2:
    aliases: wepos2
    permission: cvworldedit.selection.commands
  cvhpos1:
    aliases: wehpos1
    permission: cvworldedit.selection.commands
  cvhpos2:
    aliases: wehpos2
    permission: cvworldedit.selection.commands
  cvexpand:
    aliases: weexpand
    permission: cvworldedit.selection.commands
  cvcontract:
    aliases: wecontract
    permission: cvworldedit.selection.commands
  cvshift:
    aliases: weshift
    permission: cvworldedit.selection.commands
  cvselection:
    aliases: weselection
    permission: cvworldedit.selection.commands
  cvsel:
    aliases: wesel
    permission: cvworldedit.selection.commands
  cvsize:
    aliases: wesize
    permission: cvworldedit.selection.commands
  cvcut:
    aliases: wecut
    permission: cvworldedit.cut.commmand
  cvcopy:
    aliases: wecopy
    permission: cvworldedit.copy.command
  cvpaste:
    aliases: wepaste
    permission: cvworldedit.paste.command
  cvrotate:
    aliases: werotate
    permission: cvworldedit.rotate.command
  cvflip:
    aliases: weflip
    permission: cvworldedit.flip.command
  cvset:
    aliases: weset
    permission: cvworldedit.set.command
  cvwalls:
    aliases: wewalls
    permission: cvworldedit.walls.command
  cvfaces:
    aliases: wefaces
    permission: cvworldedit.faces.command
  cvreplace:
    aliases: wereplace
    permission: cvworldedit.replace.command
  cvrep:
    aliases: werep
    permission: cvworldedit.replace.command
  cvstack:
    aliases: westack
    permission: cvworldedit.stack.command
  cvmove:
    aliases: wemove
    permission: cvworldedit.move.commmand
  cvundo:
    aliases: weundo
    permission: cvworldedit.undo.command
  cvredo:
    aliases: weredo
    permission: cvworldedit.redo.command
  cvclearhistory:
    aliases: weclearhistory
    permission: cvworldedit.clearhistory.command
  cvclearclipboard:
    aliases: weclearclipboard
    permission: cvworldedit.clearclipboard.command
  cvclearplot:
    aliases: weclearplot
    permission: cvworldedit.clearplot.command